services:
  - type: web
    name: dawn-running-weather
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=true playwright install chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS
        value: "true"
    autoDeploy: true
